/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static formularios.Cliente.txtnombre;

/**
 *
 * @author Administrador
 */
public class Empleados extends javax.swing.JFrame {
     int tecla;
     conexion conecta = new conexion();
    Connection cn = conecta.conexion();

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
        Limpiar();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarcbCiudad();
        txtcedula.requestFocus();
        
        txtcod.setEnabled(false);
        txtid.setEnabled(false);
    }
    
    public void Limpiar() {
        
        txtnombre.setText("");
        txtcedula.setText("");
        txtdireccion.setText("");
        txttelefono.setText("");
    }
            
   

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        cbsexo = new javax.swing.JComboBox<>();
        cbciudad = new javax.swing.JComboBox<>();
        bnguardar = new javax.swing.JButton();
        bncancelar = new javax.swing.JButton();
        txtcod = new javax.swing.JTextField();
        bnmodificar = new javax.swing.JButton();
        bneliminar = new javax.swing.JButton();
        bnconsultar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("MANTENIMIENTO EMPLEADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 30, 220, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("CEDULA:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 100, 70, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 154, 70, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("DIRECCION:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 200, 70, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("TELEFONO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 250, 70, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("SEXO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 300, 40, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("CIUDAD:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 354, 60, 20);

        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcedula);
        txtcedula.setBounds(120, 100, 118, 30);

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre);
        txtnombre.setBounds(120, 150, 261, 30);

        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });
        getContentPane().add(txtdireccion);
        txtdireccion.setBounds(120, 200, 261, 30);

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txttelefono);
        txttelefono.setBounds(120, 250, 107, 30);

        cbsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masculino", "femenino" }));
        cbsexo.setSelectedIndex(-1);
        getContentPane().add(cbsexo);
        cbsexo.setBounds(120, 300, 116, 30);

        getContentPane().add(cbciudad);
        cbciudad.setBounds(120, 360, 116, 30);

        bnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar1.png"))); // NOI18N
        bnguardar.setText("GUARDAR");
        bnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(bnguardar);
        bnguardar.setBounds(480, 100, 150, 60);

        bncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        bncancelar.setText("CANCELAR");
        bncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bncancelar);
        bncancelar.setBounds(480, 390, 140, 60);

        txtcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodActionPerformed(evt);
            }
        });
        getContentPane().add(txtcod);
        txtcod.setBounds(260, 360, 44, 30);

        bnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.jpg"))); // NOI18N
        bnmodificar.setText("MODIFAR");
        bnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(bnmodificar);
        bnmodificar.setBounds(480, 190, 150, 60);

        bneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        bneliminar.setText("ELIMINAR");
        bneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bneliminar);
        bneliminar.setBounds(480, 280, 150, 60);

        bnconsultar.setText("...");
        bnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(bnconsultar);
        bnconsultar.setBounds(260, 100, 45, 30);

        txtid.setEditable(false);
        getContentPane().add(txtid);
        txtid.setBounds(320, 100, 36, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, -10, 730, 570);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(370, 290, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncancelarActionPerformed
       new Menu().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bncancelarActionPerformed

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        int lim=10;
        if(txtcedula.getText().length()==lim){
            evt.consume();
        }
        char c=evt.getKeyChar();
        if (c<'0'|| c>'9' ){
            evt.consume();
        }
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        int limite=50;
        if(txtnombre.getText().length()==limite){
            evt.consume();
        } 
        char c=evt.getKeyChar();
        if (!(c<'0'|| c>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        int limite=50;
        if(txtdireccion.getText().length()==limite){
            evt.consume();
        }
        char c=evt.getKeyChar();
        if (!(c<'0'|| c>'9')){
            evt.consume();
        }
                
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
       int lim=10;
        if(txttelefono.getText().length()==lim){
            evt.consume();
        }
        char c=evt.getKeyChar();
        if (c<'0'|| c>'9' ){
            evt.consume();
        }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void bnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnguardarActionPerformed
        PreparedStatement pst = null;
   try{
       pst = cn.prepareStatement("INSERT INTO empleados(cedula,nombre,direccion,telefono,sexo,id_ciudad)VALUES(?,?,?,?,?,?)");
       pst.setString(1, txtcedula.getText().toUpperCase());
       pst.setString(2, txtnombre.getText().toUpperCase());
       pst.setString(3, txtdireccion.getText().toUpperCase()); 
       pst.setString(4, txttelefono.getText().toUpperCase());        
       pst.setString(5, cbsexo.getSelectedItem().toString());
       pst.setInt(6, cbciudad.getSelectedIndex()+1);
       pst.executeUpdate();
       JOptionPane.showMessageDialog(null,"registro grabado exitosamente");
       Limpiar();
      
    }catch (SQLException ex){
       System.out.println(ex.getMessage());
    } 
   
   
    }//GEN-LAST:event_bnguardarActionPerformed

    public void CodigoCiudad(){
              
        try{
            
            PreparedStatement pst = cn.prepareCall("SELECT id_ciudad FROM ciudades WHERE nombre = '" + (String)cbciudad.getSelectedItem()+"'" );
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                txtcod.setText(rs.getString(1));
            }
            
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(),"ERROR",JOptionPane.ERROR_MESSAGE);
            
        }
    }
    private void bnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnmodificarActionPerformed
        bncancelar.setEnabled(true);
        bnguardar.setEnabled(true);
        PreparedStatement pst = null;
        try{
            pst=cn.prepareStatement("UPDATE empleados set cedula=?,nombre=?,direccion=?,telefono=?,sexo=?,id_ciudad=? where id_empleado="+txtid.getText());
            pst.setString(1,txtcedula.getText().toUpperCase());
            pst.setString(2,txtnombre.getText().toUpperCase());
            pst.setString(3,txtdireccion.getText().toUpperCase()); 
            pst.setString(4, txttelefono.getText().toUpperCase());
            pst.setString(5, cbsexo.getSelectedItem().toString());
            pst.setInt(6, cbciudad.getSelectedIndex()+1);
            
            pst.executeQuery();
            JOptionPane.showMessageDialog(null, "registro modificado exitosamente");
            Limpiar();
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_bnmodificarActionPerformed

    private void bneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneliminarActionPerformed
        bncancelar.setEnabled(true);
        bnguardar.setEnabled(true);
        PreparedStatement pst = null;
        try{
            pst=cn.prepareStatement("delete from empleados where id_empleado=?");
            pst.setInt(1, Integer.parseInt(txtid.getText()));
            pst.executeQuery();
            JOptionPane.showMessageDialog(null,"registro eliminado exitosamente");
            Limpiar();
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_bneliminarActionPerformed

    private void bnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnconsultarActionPerformed
         mostrarDatos(txtcedula.getText());
       bnmodificar.setEnabled(true);
       bnguardar.setEnabled(false);
       bneliminar.setEnabled(true);

    }//GEN-LAST:event_bnconsultarActionPerformed

    private void txtcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodActionPerformed

    public void cargarcbCiudad(){
        try{
            Statement st = cn.createStatement();
            String sql= "Select * from ciudades";
            ResultSet rs = st.executeQuery(sql);
            cbciudad.addItem("");
            while(rs.next()){
                cbciudad.addItem(rs.getString(2));
            }
         
        }catch(SQLException ex){
            
        }
    }
    public void mostrarDatos(String valor){
     String sql ="";
     sql="select * from empleados where cedula='"+ valor + "'";
     try{
           Statement st = cn.createStatement();
           ResultSet rs= st.executeQuery(sql);
           while(rs.next()){
               txtcedula.setText(rs.getString(2));             
              txtnombre.setText(rs.getString(3));              
              txtdireccion.setText(rs.getString(4)); 
              txttelefono.setText(rs.getString(5));
              cbsexo.setSelectedItem(rs.getString(6));
              txtcod.setText(rs.getString(7));
              txtid.setText(rs.getString(1));
              llenarciudad(txtcod.getText());
           }
        }catch(SQLException ex){
        
        }
    }
    public void llenarciudad(String valor){
      try{
          Statement st= cn.createStatement();
          String sql="select * from ciudades where id_ciudad='" + valor + "'";
          ResultSet rs= st.executeQuery(sql);
          while(rs.next()){
              cbciudad.setSelectedItem(rs.getString(2));
          }
      }catch(SQLException ex){
          
      }
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bncancelar;
    private javax.swing.JButton bnconsultar;
    private javax.swing.JButton bneliminar;
    private javax.swing.JButton bnguardar;
    private javax.swing.JButton bnmodificar;
    private javax.swing.JComboBox<String> cbciudad;
    private javax.swing.JComboBox<String> cbsexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

    
    
    





}
