/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import conexion.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrador
 */
public class Factura extends javax.swing.JFrame {
DefaultTableModel model=new DefaultTableModel();

int cont = 0;

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
       
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        
    }
    public void Limpiar(){
        txtcedula.setText("");
        txtnombre.setText("");
        txtfecha.setText("");
        txtvendedor.setText("");
        txtnumfactura.setText("");
        txtpre.setText("");
        txtcant.setText("");
        txttotal.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bnimprimir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        bncalcularfactura = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnumfactura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtvendedor = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        bncancelar = new javax.swing.JButton();
        bnconsultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpre = new javax.swing.JTextField();
        txtcant = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(870, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("FACTURA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 20, 90, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("CLIENTE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 160, 60, 20);

        jLabel4.setText("C.I.:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 120, 40, 20);

        bnimprimir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imprimir.jpg"))); // NOI18N
        bnimprimir.setText("IMPRIMIR");
        bnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnimprimirActionPerformed(evt);
            }
        });
        getContentPane().add(bnimprimir);
        bnimprimir.setBounds(480, 520, 170, 70);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel14.setText("TOTAL DE COMPRA:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 584, 130, 20);

        bncalcularfactura.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bncalcularfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calcular.jpg"))); // NOI18N
        bncalcularfactura.setText("CALCULAR");
        bncalcularfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncalcularfacturaActionPerformed(evt);
            }
        });
        getContentPane().add(bncalcularfactura);
        bncalcularfactura.setBounds(290, 520, 160, 70);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel16.setText("COMERCIAL \"YENIS\"");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(130, 60, 150, 30);

        txtnombre.setMinimumSize(new java.awt.Dimension(9, 20));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre);
        txtnombre.setBounds(140, 160, 230, 30);

        txtcedula.setMinimumSize(new java.awt.Dimension(9, 20));
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcedula);
        txtcedula.setBounds(140, 110, 130, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Nº FACTURA:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 100, 100, 30);

        txtnumfactura.setEditable(false);
        txtnumfactura.setMinimumSize(new java.awt.Dimension(9, 20));
        txtnumfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumfacturaActionPerformed(evt);
            }
        });
        txtnumfactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumfacturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtnumfactura);
        txtnumfactura.setBounds(680, 100, 40, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("FECHA:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 199, 50, 20);

        txtfecha.setMinimumSize(new java.awt.Dimension(9, 20));
        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });
        txtfecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfechaKeyTyped(evt);
            }
        });
        getContentPane().add(txtfecha);
        txtfecha.setBounds(140, 200, 130, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("VENDEDOR:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 240, 80, 20);

        txtvendedor.setMinimumSize(new java.awt.Dimension(9, 20));
        txtvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvendedorActionPerformed(evt);
            }
        });
        txtvendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvendedorKeyTyped(evt);
            }
        });
        getContentPane().add(txtvendedor);
        txtvendedor.setBounds(140, 240, 240, 30);

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        txttotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttotalKeyTyped(evt);
            }
        });
        getContentPane().add(txttotal);
        txttotal.setBounds(180, 590, 87, 30);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CANTIDAD", "DESCRIPCION", "PRECIO UNITARIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tab);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 300, 830, 170);

        bncancelar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        bncancelar.setText("CANCELAR");
        bncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bncancelar);
        bncancelar.setBounds(690, 520, 150, 70);

        bnconsultar.setText("...");
        bnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(bnconsultar);
        bnconsultar.setBounds(320, 110, 60, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("PRECIO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 500, 60, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("CANTIDAD:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 540, 80, 20);

        txtpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreActionPerformed(evt);
            }
        });
        getContentPane().add(txtpre);
        txtpre.setBounds(180, 490, 60, 30);

        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantActionPerformed(evt);
            }
        });
        getContentPane().add(txtcant);
        txtcant.setBounds(180, 540, 50, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-10, -10, 900, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnimprimirActionPerformed
       
      MessageFormat header = new MessageFormat ("Tabla de clientes");
        MessageFormat footer = new MessageFormat ("Pagina {0, number, interger}");
        try{
            tab.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }catch (java.awt.print.PrinterException e){
            System.err.format("Error, no se puede imprimir %s %n ", e.getMessage());
        }
           
    }//GEN-LAST:event_bnimprimirActionPerformed

    private void bncalcularfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncalcularfacturaActionPerformed
      int precio,cantidad,c =1;
        precio = Integer.parseInt(txtpre.getText());
        cantidad=Integer.parseInt(txtcant.getText());
        txttotal.setText(String.valueOf(precio*cantidad));
       
      
       txtnumfactura.setText(String.valueOf(c++));
       
         
    }//GEN-LAST:event_bncalcularfacturaActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
         
        char c = evt.getKeyChar();
        if((c<'a' || c>'z')&& (c<'A'|| c >'Z')&& (c!=32)){
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
         char c = evt.getKeyChar();
         if(c<'0' || c>'9'){
             evt.consume();
        }
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtfechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfechaKeyTyped
         char c = evt.getKeyChar();
         if((c<'0' || c>'9')&&(c!= 47)){
             evt.consume();
        }
    }//GEN-LAST:event_txtfechaKeyTyped

    private void txtvendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvendedorKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z')&& (c<'A'|| c >'Z')&& (c!=32)){
            evt.consume();
        }
    }//GEN-LAST:event_txtvendedorKeyTyped

    private void txtnumfacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumfacturaKeyTyped
        char c = evt.getKeyChar();
         if(c<'0' || c>'9'){
             evt.consume();
        }
    }//GEN-LAST:event_txtnumfacturaKeyTyped

    private void txttotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalKeyTyped
        char c = evt.getKeyChar();
         if((c<'0' || c>'9')&&(c!= 188)){
             evt.consume();
        }
    }//GEN-LAST:event_txttotalKeyTyped

    private void txtnumfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumfacturaActionPerformed
      
       
       
    }//GEN-LAST:event_txtnumfacturaActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
         
        
        
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed
       
       
    }//GEN-LAST:event_txtcedulaActionPerformed

    private void bncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bncancelarActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void bnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnconsultarActionPerformed
        mostrarDatos(txtcedula.getText());
       
    }//GEN-LAST:event_bnconsultarActionPerformed

    private void txtpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreActionPerformed

    private void txtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantActionPerformed

    private void txtvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvendedorActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

     conexion conecta = new conexion();
        Connection cn = conecta.conexion();
     public void mostrarDatos(String valor){
     String sql ="";
     sql="select * from clientes where cedula='"+ valor + "'";
     try{
           Statement st = cn.createStatement();
           ResultSet rs= st.executeQuery(sql);
           while(rs.next()){
                    
              txtnombre.setText(rs.getString(3));
               }
        }catch(SQLException ex){
           System.out.println(ex.getMessage());
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bncalcularfactura;
    private javax.swing.JButton bncancelar;
    private javax.swing.JButton bnconsultar;
    public javax.swing.JButton bnimprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tab;
    public static javax.swing.JTextField txtcant;
    public static javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtfecha;
    public static javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnumfactura;
    public static javax.swing.JTextField txtpre;
    public static javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtvendedor;
    // End of variables declaration//GEN-END:variables
}
