
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LSI-LAB24
 */
public class Login extends javax.swing.JFrame {
    PreparedStatement pst = null;
    conexion conecta = new conexion();
    Connection cn = conecta.conexion();
    ResultSet rs= null;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        bnaceptar = new javax.swing.JButton();
        bncancelar = new javax.swing.JButton();
        txtcontraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("USUARIO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 120, 80, 25);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("PASSWORD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 170, 70, 20);

        txtusuario.setMinimumSize(new java.awt.Dimension(9, 20));
        getContentPane().add(txtusuario);
        txtusuario.setBounds(140, 120, 160, 30);

        bnaceptar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar.jpg"))); // NOI18N
        bnaceptar.setText("ACEPTAR");
        bnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnaceptarActionPerformed(evt);
            }
        });
        getContentPane().add(bnaceptar);
        bnaceptar.setBounds(60, 260, 143, 59);

        bncancelar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        bncancelar.setText("CANCELAR");
        bncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bncancelar);
        bncancelar.setBounds(260, 260, 141, 59);

        txtcontraseña.setMinimumSize(new java.awt.Dimension(9, 20));
        txtcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtcontraseña);
        txtcontraseña.setBounds(140, 170, 109, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -70, 440, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnaceptarActionPerformed
        String tipo_usuario="";
        String sql= "SELECT * from login where usuario=? and contraseña=?" ;
        try{
            pst = cn.prepareStatement(sql);
            pst.setString(1, txtusuario.getText());
            pst.setString(2,txtcontraseña.getText());
            rs= pst.executeQuery();
            if(rs.next()){
                //tipo_usuario = rs.getString(1);
                JOptionPane.showMessageDialog(null,"BIENVENIDO(A)" + txtusuario.getText(), "Login\n " , JOptionPane.INFORMATION_MESSAGE);
                Menu me = new Menu();
                me.setVisible(true);
                Menu.login.setText(txtusuario.getText());
                this.setVisible(false);                
            }
            else{
                JOptionPane.showMessageDialog(null, "Login o password incorrecto" , "ERROR\n" , JOptionPane.ERROR_MESSAGE);
                
            }
        }catch(Exception ex ){
            JOptionPane.showMessageDialog(null,"ERROR de conexion", "EROR\n" + ex, JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_bnaceptarActionPerformed

    private void bncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bncancelarActionPerformed

    private void txtcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnaceptar;
    private javax.swing.JButton bncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtcontraseña;
    public static javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
