/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Administrador
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bncliente = new javax.swing.JButton();
        bnproducto = new javax.swing.JButton();
        bnempleados = new javax.swing.JButton();
        bnsalir = new javax.swing.JButton();
        bnregistro = new javax.swing.JButton();
        bnciudades = new javax.swing.JButton();
        bntalla = new javax.swing.JButton();
        bnmarca = new javax.swing.JButton();
        bntipo_calzado = new javax.swing.JButton();
        login = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 570));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("MENU DE MANTENIMIENTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 60, 300, 30);

        bncliente.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bncliente.setText("CLIENTES");
        bncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnclienteActionPerformed(evt);
            }
        });
        getContentPane().add(bncliente);
        bncliente.setBounds(30, 80, 110, 60);

        bnproducto.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnproducto.setText("PRODUCTOS");
        bnproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnproductoActionPerformed(evt);
            }
        });
        getContentPane().add(bnproducto);
        bnproducto.setBounds(30, 240, 110, 60);

        bnempleados.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnempleados.setText("EMPLEADOS");
        bnempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnempleadosActionPerformed(evt);
            }
        });
        getContentPane().add(bnempleados);
        bnempleados.setBounds(30, 160, 110, 60);

        bnsalir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnsalir.setText("SALIR");
        bnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(bnsalir);
        bnsalir.setBounds(580, 300, 100, 60);

        bnregistro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnregistro.setText("REGISTROS");
        bnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnregistroActionPerformed(evt);
            }
        });
        getContentPane().add(bnregistro);
        bnregistro.setBounds(330, 380, 100, 60);

        bnciudades.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnciudades.setText("CIUDADES");
        bnciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnciudadesActionPerformed(evt);
            }
        });
        getContentPane().add(bnciudades);
        bnciudades.setBounds(30, 310, 110, 60);

        bntalla.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bntalla.setText("TALLAS");
        bntalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntallaActionPerformed(evt);
            }
        });
        getContentPane().add(bntalla);
        bntalla.setBounds(30, 380, 110, 60);

        bnmarca.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnmarca.setText("MARCAS");
        bnmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnmarcaActionPerformed(evt);
            }
        });
        getContentPane().add(bnmarca);
        bnmarca.setBounds(450, 380, 110, 60);

        bntipo_calzado.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bntipo_calzado.setText("TIPOS DE CALZADO");
        bntipo_calzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntipo_calzadoActionPerformed(evt);
            }
        });
        getContentPane().add(bntipo_calzado);
        bntipo_calzado.setBounds(160, 380, 150, 60);

        login.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        login.setForeground(java.awt.Color.white);
        login.setText("HOLA");
        getContentPane().add(login);
        login.setBounds(350, 150, 140, 40);

        jButton1.setText("MATERIALES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 380, 110, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu_1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 750, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnclienteActionPerformed
         new Cliente().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bnclienteActionPerformed

    private void bnproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnproductoActionPerformed
         new Producto().setVisible(true);
       this.setVisible(false); 
    }//GEN-LAST:event_bnproductoActionPerformed

    private void bnempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnempleadosActionPerformed
        new Empleados().setVisible(true);
       this.setVisible(false);  
    }//GEN-LAST:event_bnempleadosActionPerformed

    private void bnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bnsalirActionPerformed

    private void bnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnregistroActionPerformed
        new Registro().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bnregistroActionPerformed

    private void bntallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntallaActionPerformed
        new Talla().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntallaActionPerformed

    private void bnciudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnciudadesActionPerformed
        new Ciudades().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bnciudadesActionPerformed

    private void bnmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnmarcaActionPerformed
        new marca().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bnmarcaActionPerformed

    private void bntipo_calzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntipo_calzadoActionPerformed
        new tipo_calzado().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntipo_calzadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Material().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnciudades;
    private javax.swing.JButton bncliente;
    private javax.swing.JButton bnempleados;
    private javax.swing.JButton bnmarca;
    private javax.swing.JButton bnproducto;
    private javax.swing.JButton bnregistro;
    private javax.swing.JButton bnsalir;
    private javax.swing.JButton bntalla;
    private javax.swing.JButton bntipo_calzado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel login;
    // End of variables declaration//GEN-END:variables
}
