/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import conexion.conexion;
import identidades.Marca_i;
import identidades.Material_i;
import identidades.Producto_i;
import identidades.Talla_i;
import identidades.Tipo_Calzado_i;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


import javax.swing.JOptionPane;
import reprository.Marca_Repository;
import reprository.Material_Repository;
import reprository.Producto_Repository;
import reprository.Talla_Repository;
import reprository.Tipo_Repository;


/**
 *
 * @author Administrador
 */
public class Producto extends javax.swing.JFrame {
    conexion conecta = new conexion();
    Connection cn = conecta.conexion();
    Producto_Repository pr = new Producto_Repository();
    Talla_Repository tr = new Talla_Repository();
    Marca_Repository mr= new Marca_Repository();
    Material_Repository mare = new Material_Repository();
    Tipo_Repository tre = new Tipo_Repository();
    

    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
        cargarcbTalla();
        cargarcbMarca();
        cargarcbMaterial();
        cargarcbTipoCalzado();
         Limpiar();
         txtmarca.setEnabled(false);
         txttalla.setEnabled(false);
         txtmaterial.setEnabled(false);
         txttipo.setEnabled(false);
         txtid.setEnabled(true);
        
        this.setLocationRelativeTo(null);
        this.setResizable(false);       
        txttalla.requestFocus();
        txttalla.setVisible(false);
        
    }
    public void cargarcbTalla(){
        String sql= "Select * from tallas";
        try{
            Statement st = cn.createStatement();
            
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                cbtalla.addItem(rs.getString(2));
            }
         
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "exception 2 "+ex);
        }
    }public void cargarcbMarca(){
        String sql= "Select * from marcas";
        try{
            Statement st = cn.createStatement();
            
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                cbmarca.addItem(rs.getString(2));
            }
         
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "exception 2 "+ex);
        }
    }
    public void cargarcbMaterial(){
        String sql= "Select * from materiales";
        try{
            Statement st = cn.createStatement();
            
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                cbmaterial.addItem(rs.getString(2));
            }
         
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "exception 2 "+ex);
        }
    }
    public void cargarcbTipoCalzado(){
        String sql= "Select * from tipos_calzado";
        try{
            Statement st = cn.createStatement();
            
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                cbtipocalzado.addItem(rs.getString(2));
            }
         
        }catch(SQLException ex){
           JOptionPane.showMessageDialog(null, "exception 2 "+ex); 
        }
    }
    public void Limpiar() {
        
        txtprecio.setText("");
        txtcantidad.setText("");
        cbcolor.setSelectedItem(-1);
        cbtalla.setSelectedItem(-1);
        cbmarca.setSelectedItem(-1);
        cbmaterial.setSelectedItem(-1);
        cbtipocalzado.setSelectedItem(-1);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bnguardar = new javax.swing.JButton();
        bncancelar = new javax.swing.JButton();
        cbcolor = new javax.swing.JComboBox<>();
        cbtalla = new javax.swing.JComboBox<>();
        txtcantidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbmarca = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbmaterial = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbtipocalzado = new javax.swing.JComboBox<>();
        txttalla = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        txtmaterial = new javax.swing.JTextField();
        bnmodificar = new javax.swing.JButton();
        bneliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        bnconsultar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 650));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("MANTENIMIENTO PRODUCTO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 24, 210, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 60, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("PRECIO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 110, 50, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("CANTIDAD:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 150, 80, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("COLOR:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 50, 14);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("TALLA:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 260, 50, 14);

        bnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar1.png"))); // NOI18N
        bnguardar.setText("GUARDAR");
        bnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(bnguardar);
        bnguardar.setBounds(450, 160, 150, 60);

        bncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        bncancelar.setText("CANCELAR");
        bncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bncancelar);
        bncancelar.setBounds(450, 460, 150, 60);

        cbcolor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rosado", "negro", "blanco", "rojo", "azul", "morado", "cafe", "plata", "beich" }));
        cbcolor.setSelectedIndex(-1);
        cbcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcolorActionPerformed(evt);
            }
        });
        getContentPane().add(cbcolor);
        cbcolor.setBounds(150, 200, 108, 30);

        cbtalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtallaActionPerformed(evt);
            }
        });
        getContentPane().add(cbtalla);
        cbtalla.setBounds(150, 260, 108, 30);

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtcantidad);
        txtcantidad.setBounds(150, 150, 108, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("ZAPATO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 70, 60, 20);

        txtprecio.setMinimumSize(new java.awt.Dimension(9, 20));
        txtprecio.setPreferredSize(new java.awt.Dimension(9, 20));
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });
        getContentPane().add(txtprecio);
        txtprecio.setBounds(150, 110, 108, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("MARCA:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 320, 50, 14);

        cbmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmarcaActionPerformed(evt);
            }
        });
        getContentPane().add(cbmarca);
        cbmarca.setBounds(150, 320, 108, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("MATERIAL:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 380, 80, 14);

        cbmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmaterialActionPerformed(evt);
            }
        });
        getContentPane().add(cbmaterial);
        cbmaterial.setBounds(150, 380, 108, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setText("TIPO DE CALZADO:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 440, 120, 14);

        cbtipocalzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipocalzadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbtipocalzado);
        cbtipocalzado.setBounds(150, 440, 106, 30);

        txttalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttallaActionPerformed(evt);
            }
        });
        getContentPane().add(txttalla);
        txttalla.setBounds(270, 260, 47, 30);
        getContentPane().add(txtmarca);
        txtmarca.setBounds(270, 320, 47, 30);

        txttipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoActionPerformed(evt);
            }
        });
        getContentPane().add(txttipo);
        txttipo.setBounds(270, 440, 47, 30);

        txtmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaterialActionPerformed(evt);
            }
        });
        getContentPane().add(txtmaterial);
        txtmaterial.setBounds(270, 380, 47, 30);

        bnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.jpg"))); // NOI18N
        bnmodificar.setText("MODIFICAR");
        bnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(bnmodificar);
        bnmodificar.setBounds(450, 260, 150, 60);

        bneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        bneliminar.setText("ELIMINAR");
        bneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bneliminar);
        bneliminar.setBounds(450, 360, 150, 60);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("ID_PRODUCTO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 90, 100, 14);

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid);
        txtid.setBounds(500, 80, 59, 30);

        bnconsultar.setText("...");
        bnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(bnconsultar);
        bnconsultar.setBounds(280, 110, 50, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto1.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-30, -60, 770, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnguardarActionPerformed
        Marca_i mar = mr.getMarcaNombre(cbmarca.getSelectedItem().toString());
        Material_i mate = mare.getMaterialNombre(cbmaterial.getSelectedItem().toString());
        Talla_i ta = tr.getTallaNumero(Integer.parseInt(cbtalla.getSelectedItem().toString()));
        Tipo_Calzado_i ti = tre.getTipoNombre(cbtipocalzado.getSelectedItem().toString());
        Producto_i pro = new Producto_i (txtprecio.getText(),txtcantidad.getText(),cbcolor.getSelectedItem().toString(),ta,mar,mate,ti);
         pr.Ingresar(pro);
        
        Factura abrir= new Factura();
        abrir.setVisible(true);
        
        Factura.txtpre.setText(txtprecio.getText());
        Factura.txtcant.setText(txtcantidad.getText());
   Limpiar();
                
    }//GEN-LAST:event_bnguardarActionPerformed

    
    private void bncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncancelarActionPerformed
       new Menu().setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_bncancelarActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void cbcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcolorActionPerformed

    private void cbmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmarcaActionPerformed

    private void cbmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmaterialActionPerformed

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
          char c = evt.getKeyChar();
         if((c<'0' || c>'9')&&(c!= 188)){
             evt.consume();
        }
    }//GEN-LAST:event_txtprecioKeyTyped

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
         char c = evt.getKeyChar();
         if(c<'0' || c>'9'){
             evt.consume();
        }
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txttipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoActionPerformed

    private void txtmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaterialActionPerformed

    private void txttallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttallaActionPerformed

    private void bnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnmodificarActionPerformed
        bnguardar.setEnabled(true);
        bncancelar.setEnabled(true);
         Marca_i mar = mr.getMarcaNombre(cbmarca.getSelectedItem().toString());
        Material_i mate = mare.getMaterialNombre(cbmaterial.getSelectedItem().toString());
        Talla_i ta = tr.getTallaNumero(Integer.parseInt(cbtalla.getSelectedItem().toString()));
        Tipo_Calzado_i ti = tre.getTipoNombre(cbtipocalzado.getSelectedItem().toString());
        Producto_i pro = new Producto_i (txtprecio.getText(),txtcantidad.getText(),cbcolor.getSelectedItem().toString(),ta,mar,mate,ti);
        pr.Modificar(Integer.parseInt(txtid.getText()), pro);
            Limpiar();
           
    }//GEN-LAST:event_bnmodificarActionPerformed

    private void bneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneliminarActionPerformed
        bncancelar.setEnabled(true);
        bnguardar.setEnabled(true); 
        pr.Eliminar(Integer.parseInt(txtid.getText()));
            Limpiar();
           
    }//GEN-LAST:event_bneliminarActionPerformed

    private void bnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnconsultarActionPerformed
        
       bnmodificar.setEnabled(true);
       bnguardar.setEnabled(false);
       bneliminar.setEnabled(true);
       Producto_i product = (Producto_i)pr.getProducto(txtprecio.getText());
       txtid.setText(Integer.toString(product.getId_producto()));
       txtprecio.setText(product.getPrecio());
       txtcantidad.setText(product.getCantidad());
       cbcolor.setSelectedItem(product.getColor());
       cbtalla.setSelectedItem(product.getTalla().getNumero());
       cbmarca.setSelectedItem(product.getMarca().getNombre());
       cbmaterial.setSelectedItem(product.getMaterial().getNombre());
       cbtipocalzado.setSelectedItem(product.getTipo().getNombre());

    }//GEN-LAST:event_bnconsultarActionPerformed

    private void cbtipocalzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipocalzadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipocalzadoActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void cbtallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtallaActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_cbtallaActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bncancelar;
    private javax.swing.JButton bnconsultar;
    private javax.swing.JButton bneliminar;
    private javax.swing.JButton bnguardar;
    private javax.swing.JButton bnmodificar;
    public javax.swing.JComboBox<String> cbcolor;
    public javax.swing.JComboBox<String> cbmarca;
    public javax.swing.JComboBox<String> cbmaterial;
    public javax.swing.JComboBox<String> cbtalla;
    public javax.swing.JComboBox<String> cbtipocalzado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmaterial;
    public static javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttalla;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables

    
    
    
    
}
