/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Administrador
 */
public class Registro extends javax.swing.JFrame {
   conexion conecta = new conexion();
    Connection cn = conecta.conexion();

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
       
        this.setLocationRelativeTo(null);
        this.setResizable(false);       
        
    }
    public void Limpiar(){
        txtcedula.setText("");
        txtnombre.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        bnbuscar = new javax.swing.JButton();
        bncancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cedula = new javax.swing.JRadioButton();
        nombre = new javax.swing.JRadioButton();
        txtcedula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("REGISTRO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 30, 90, 30);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_cliente", "cedula", "nombre", "direccion", "telefono", "sexo", "ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tab);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 290, 690, 120);

        bnbuscar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_buscar.png"))); // NOI18N
        bnbuscar.setText("BUSCAR");
        bnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bnbuscar);
        bnbuscar.setBounds(560, 70, 140, 59);

        bncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        bncancelar.setText("CANCELAR");
        bncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bncancelar);
        bncancelar.setBounds(560, 140, 140, 60);

        jPanel1.setLayout(null);

        buttonGroup1.add(cedula);
        cedula.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cedula.setText("CEDULA:");
        cedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cedulaMouseClicked(evt);
            }
        });
        jPanel1.add(cedula);
        cedula.setBounds(30, 30, 80, 23);

        buttonGroup1.add(nombre);
        nombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nombre.setText("NOMBRE:");
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });
        jPanel1.add(nombre);
        nombre.setBounds(30, 80, 90, 23);

        txtcedula.setPreferredSize(new java.awt.Dimension(9, 20));
        txtcedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcedulaMouseClicked(evt);
            }
        });
        jPanel1.add(txtcedula);
        txtcedula.setBounds(129, 30, 140, 30);

        txtnombre.setMinimumSize(new java.awt.Dimension(9, 20));
        jPanel1.add(txtnombre);
        txtnombre.setBounds(136, 80, 230, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 90, 390, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 850, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cedulaMouseClicked
        txtcedula.setEnabled(true);
        txtnombre.setEnabled(false);
    }//GEN-LAST:event_cedulaMouseClicked

    private void txtcedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcedulaMouseClicked
        
    }//GEN-LAST:event_txtcedulaMouseClicked

    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
        txtnombre.setEnabled(true);
        txtcedula.setEnabled(false);
    }//GEN-LAST:event_nombreMouseClicked

    private void bncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bncancelarActionPerformed

    private void bnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnbuscarActionPerformed
        SQL();
        Limpiar();
    }//GEN-LAST:event_bnbuscarActionPerformed

    public void SQL(){
        String sql = "";
        if(txtcedula.getText().equals("") && cedula.isSelected()){
            sql = "SELECT clientes.id_cliente,clientes.cedula,clientes.nombre,clientes.direccion,clientes.telefono,clientes.sexo,ciudades.nombre FROM clientes" 
                + " INNER JOIN ciudades ON clientes.id_ciudad = ciudades.id_ciudad ";
                
        }
        else{
            if(cedula.isSelected()){
                sql = "SELECT clientes.id_cliente,clientes.cedula,clientes.nombre,clientes.direccion,clientes.telefono,clientes.sexo,ciudades.nombre FROM clientes"                 
                + " INNER JOIN ciudades ON clientes.id_ciudad = ciudades.id_ciudad WHERE clientes.cedula ='" + txtcedula.getText() + "'";
            }
            else{
                
                    if(nombre.isSelected()){
                    sql = "SELECT clientes.id_cliente,clientes.cedula,clientes.nombre,clientes.direccion,clientes.telefono,clientes.sexo,ciudades.nombre FROM clientes"                      
                    + " INNER JOIN ciudades ON clientes.id_ciudad = ciudades.id_ciudad WHERE clientes.nombre ='" + txtnombre.getText() + "'" ;
                }            
                
                
                
            }
        }
        Consultar(sql);        
    }
    
    public void Consultar(String sql){
        DefaultTableModel modelo = (DefaultTableModel) tab.getModel();
        modelo.setRowCount(0);
        Object [] tabla = new Object[7];
        try{
            PreparedStatement pst = cn.prepareCall(sql);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                do{
                    tabla[0] = rs.getString(1);
                    tabla[1] = rs.getString(2);
                    tabla[2] = rs.getString(3);
                    tabla[3] = rs.getString(4);
                    tabla[4] = rs.getString(5);
                    tabla[5] = rs.getString(6);
                    tabla[6] = rs.getString(7);
                    modelo.addRow(tabla);
                }while(rs.next());
                tab.setModel(modelo);
                            
            }
            else{
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRO VALOR","NOT FOUND",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        catch(SQLException exc){
            JOptionPane.showMessageDialog(null, exc.getMessage(),"WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnbuscar;
    private javax.swing.JButton bncancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton nombre;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
