/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexion.conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class tipo_calzado extends javax.swing.JFrame {
    

    /**
     * Creates new form tipo_calzado
     */
    public tipo_calzado() {
        initComponents();
        Limpiar();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        bnguardar = new javax.swing.JButton();
        bncancelar = new javax.swing.JButton();
        bnmodificar = new javax.swing.JButton();
        bneliminar = new javax.swing.JButton();
        bnconsultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("MANTENIMIENTO DE TIPOS DE CALZADO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 40, 290, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.red);
        jLabel2.setText("CODIGO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(49, 91, 60, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(49, 133, 70, 20);

        txtcodigo.setEditable(false);
        txtcodigo.setMinimumSize(new java.awt.Dimension(9, 20));
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });
        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcodigo);
        txtcodigo.setBounds(130, 81, 47, 30);

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre);
        txtnombre.setBounds(130, 129, 175, 29);

        bnguardar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar1.png"))); // NOI18N
        bnguardar.setText("GUARDAR");
        bnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(bnguardar);
        bnguardar.setBounds(10, 214, 140, 58);

        bncancelar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancelar.png"))); // NOI18N
        bncancelar.setText("CANCELAR");
        bncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bncancelar);
        bncancelar.setBounds(473, 214, 150, 58);

        bnmodificar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.jpg"))); // NOI18N
        bnmodificar.setText("MODIFICAR");
        bnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnmodificarActionPerformed(evt);
            }
        });
        getContentPane().add(bnmodificar);
        bnmodificar.setBounds(159, 214, 155, 58);

        bneliminar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        bneliminar.setText("ELIMINAR");
        bneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bneliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bneliminar);
        bneliminar.setBounds(320, 214, 147, 58);

        bnconsultar.setText("...");
        bnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(bnconsultar);
        bnconsultar.setBounds(190, 90, 50, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tipo_calzado.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 788, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
       char c = evt.getKeyChar();
         if(c<'0' || c>'9'){
             evt.consume();
        }
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char c = evt.getKeyChar();
        if((c<'a' || c>'z')&& (c<'A'|| c >'Z')&& (c!=32)){
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void bnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnguardarActionPerformed
        PreparedStatement pst = null;
            try{
               pst = cn.prepareStatement("INSERT INTO tipo_calzado(nombre)VALUES(?)");
               
               pst.setString(1, txtnombre.getText().toUpperCase());                        
               
               JOptionPane.showMessageDialog(null,"registro grabado exitosamente");
                Limpiar();
                pst.executeUpdate();     
            }catch (SQLException ex){
                System.out.println(ex.getMessage());
    }
    }//GEN-LAST:event_bnguardarActionPerformed

    private void bncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bncancelarActionPerformed
       new Menu().setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_bncancelarActionPerformed

    private void bnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnmodificarActionPerformed
         bnguardar.setEnabled(true);
        bncancelar.setEnabled(true);
        PreparedStatement pst = null;
        try{
            pst=cn.prepareStatement("UPDATE tipo_calzado set nombre=? where codigo="+txtcodigo.getText());
            
            pst.setString(1,txtnombre.getText().toUpperCase());           
            
            JOptionPane.showMessageDialog(null, "registro modificado exitosamente");
            Limpiar();
            pst.executeQuery();
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_bnmodificarActionPerformed

    private void bneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bneliminarActionPerformed
        bncancelar.setEnabled(true);
        bnguardar.setEnabled(true);
        PreparedStatement pst = null;
        try{
            pst=cn.prepareStatement("delete from tipo_calzado where codigo=?");
            pst.setInt(1, Integer.parseInt(txtcodigo.getText()));
            
            JOptionPane.showMessageDialog(null,"registro eliminadfo exitosamente");
            Limpiar();
            pst.executeQuery();
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_bneliminarActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void bnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnconsultarActionPerformed
        mostrarDatos(txtnombre.getText());
       bnmodificar.setEnabled(true);
       bnguardar.setEnabled(false);
       bneliminar.setEnabled(true);
    }//GEN-LAST:event_bnconsultarActionPerformed

    conexion conecta = new conexion();
    Connection cn = conecta.conexion();
    
    
    private void Limpiar() {
        
        txtcodigo.setText("");
        txtnombre.setText("");
        
    }
   public void mostrarDatos(String valor){
     String sql ="";
     sql="select * from tipo_calzado where nombre='"+ valor + "'";
     try{
           Statement st = cn.createStatement();
           ResultSet rs= st.executeQuery(sql);
           while(rs.next()){
               txtcodigo.setText(rs.getString(1));                            
              txtnombre.setText(rs.getString(2));
              
           }
        }catch(SQLException ex){
           System.out.println(ex.getMessage());
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tipo_calzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tipo_calzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tipo_calzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tipo_calzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tipo_calzado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bncancelar;
    private javax.swing.JButton bnconsultar;
    private javax.swing.JButton bneliminar;
    private javax.swing.JButton bnguardar;
    private javax.swing.JButton bnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
